ALTER TABLE assessment
    DROP COLUMN IF EXISTS type,
    ADD COLUMN IF NOT EXISTS type VARCHAR(30) NOT NULL;


ALTER TABLE media
    RENAME COLUMN assignment_id TO assessment_id;

ALTER TABLE media
    ADD COLUMN IF NOT EXISTS question_id VARCHAR(36);


ALTER TABLE question
    ADD COLUMN IF NOT EXISTS media_id VARCHAR(36);


ALTER TABLE media
    DROP CONSTRAINT IF EXISTS FK_MEDIA_ON_ASSIGNMENT,
    DROP CONSTRAINT IF EXISTS FK_MEDIA_ON_ANNOUNCEMENT,
    DROP CONSTRAINT IF EXISTS FK_MEDIA_ON_LESSON;

ALTER TABLE media
    ADD CONSTRAINT FK_MEDIA_ON_ASSESSMENT FOREIGN KEY (assessment_id) REFERENCES assessment (id)  ON DELETE CASCADE,
    ADD CONSTRAINT FK_MEDIA_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE;

ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_ON_MEDIA FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE;
