ALTER TABLE attempt
    ADD COLUMN IF NOT EXISTS feedback_id VARCHAR(36);

ALTER TABLE attempt
    ADD CONSTRAINT FK_FEEDBACK_ON_ATTEMPT FOREIGN KEY (feedback_id) REFERENCES feedback (id) ON DELETE CASCADE;