ALTER TABLE feedback
    ADD COLUMN IF NOT EXISTS course_id VARCHAR(36);

ALTER TABLE feedback
    ADD CONSTRAINT FK_COURSE_ON_FEEDBACK FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE;