ALTER TABLE attendance
    ADD COLUMN IF NOT EXISTS course_id VARCHAR(36);

ALTER TABLE attendance
    ADD CONSTRAINT FK_COURSE_ON_ATTENDANCE FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE;