ALTER TABLE question
    ADD COLUMN IF NOT EXIST course_id VARCHAR(36) NOT NULL;

ALTER TABLE question
    ADD COLUMN IF NOT EXIST score SMALLINT NOT NULL;

ALTER TABLE question
    ADD CONSTRAINT FK_COURSE_ON_QUESTION FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE;

ALTER TABLE question
    DROP COLUMN IF EXISTS assessment_id;