ALTER TABLE question
    ADD COLUMN IF NOT EXISTS course_id VARCHAR(36) NOT NULL;

ALTER TABLE question
    ADD COLUMN IF NOT EXISTS score INTEGER NOT NULL;

ALTER TABLE question
    ADD CONSTRAINT FK_COURSE_ON_QUESTION FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE;

ALTER TABLE question
    DROP COLUMN IF EXISTS assessment_id;